### ISSUE TITLE
Program runs, but there is no any graphics just circle..

### ISSUE THREAD

**Issue by ollipizza** [sdsgisd/DynamicSoapfilmsWithEvolvingThickness#2]
How can i run it so that it shows soap bubbles?
[Screencast from 2023年九月21日 16時56分51秒.webm](https://github.com/sdsgisd/DynamicSoapfilmsWithEvolvingThickness/assets/126404422/f6236106-f3f6-4424-9a36-b0d74a34e693)

**Comment by sdsgisd** [comment]
You seem to be running the simulation mode 0. Eulerian flow only. I recommend reading the front page of this repository.

**Comment by ollipizza** [comment]
On the front page, i couldn't find much about how to run the program, there are keyboard keys listed that change how the program works, but going through all of them didn't help.

I want to see soap bubbles thin film interference, colours, how can I achieve this?

**Comment by sdsgisd** [comment]
There is not much information about how to run the code more than written on the front page. This code does only animation of bubbles, photorealistic rendering must be done using a render that supports thin-film interference, which is outside the scope of this repository. You can still sort of see transparent bubbles with a background by changing the rendering mode. I also don't under stand what "just circle" means in the title. In the video you attached you just didn't run the code with surface deformation.

**Comment by sdsgisd** [comment]
Ok, I close this issue.
